### ISSUE TITLE
Name of classes should be aligned with PEP 8 code style

### ISSUE THREAD

**Issue by fractalliter** [M91skr/tic_tac_toe_game#1]
Name of classes should be in Pascal case based on PEP 8.

```python
class GameBoard(Turtle):
``` 
Instead of https://github.com/M91skr/tic_tac_toe_game/blob/d1db91d77d26b5ab9d78be2457df4071fc31dc35/game_board.py#L4

**Comment by M91skr** [comment]
resolved in #2
